default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: ed-sheeran-complainer_development
  username: postgres
  password: <%= ENV['ED-SHEERAN-COMPLAINER_DATABASE_PASSWORD_DEV'] %>
  host: localhost

test:
  <<: *development
  database: ed-sheeran-complainer_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  # <<: *default
  # database: ed-sheeran-complainer_production
  # username: ed-sheeran-complainer
  # password: <%= ENV['ED-SHEERAN-COMPLAINER_DATABASE_PASSWORD'] %>
